# Base image
FROM ubuntu:latest

LABEL name="All-in-One-Image" maintainer="bhange-saheb"

# Environment variables
ENV environment=Development \
    Practice=YES \
    AWS_DEFAULT_REGION=us-east-1

# Arguments for versions
ARG T_VERSION='1.6.6' \
    P_VERSION='1.8.0'

# Install dependencies
RUN apt update && apt install -y \
    jq net-tools curl wget unzip nginx iputils-ping \
    nodejs npm supervisor \
    && wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip \
    && wget https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip \
    && unzip terraform_${T_VERSION}_linux_amd64.zip \
    && unzip packer_${P_VERSION}_linux_amd64.zip \
    && chmod +x terraform packer \
    && mv terraform /usr/local/bin/terraform \
    && mv packer /usr/local/bin/packer \
    && terraform version && packer version

# Working directory
WORKDIR /app

# Copy repo files into container
COPY . .

# Install Node dependencies (if package.json exists)
RUN if [ -f package.json ]; then npm install; fi

# Configure Nginx to serve static site
RUN rm -rf /var/www/html/* \
    && cp -r . /var/www/html

# Add Supervisor config
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Expose ports
EXPOSE 80
EXPOSE 3000

# Start Nginx and Node app (if app.js exists)
CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]